# Generated by Django 4.0.3 on 2022-05-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
